########################################
# File           : Makefile            #
# Author         : Annie Beug          #
# Date           : 21-MAY-2010         #
########################################

all: 
	gcc -o mksuid mksuid.c
	
setup:
	touch sniff; chmod 0700 sniff
	
clean:
	rm mksuid
